r2p:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - odom_dummy_virtual
      - base_back_omniwheel_joint
      - base_left_omniwheel_joint
      - base_right_omniwheel_joint
      - right_arm_shoulder_pitch_joint
      - right_shoulder_pitch_shoulder_yaw_joint
      - right_shoulder_yaw_upper_arm_joint
      - right_upper_arm_elbow_joint
      - right_meta_thumb_prox_joint
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    []
  r2p_position_controller:
    type: position_controllers/JointPositionController
    joints:
      - right_arm_shoulder_pitch_joint
      - right_shoulder_pitch_shoulder_yaw_joint
      - right_shoulder_yaw_upper_arm_joint
      - right_upper_arm_elbow_joint
      - right_meta_thumb_prox_joint
    gains:
      right_arm_shoulder_pitch_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_shoulder_pitch_shoulder_yaw_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_shoulder_yaw_upper_arm_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_upper_arm_elbow_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      right_meta_thumb_prox_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1